### PR TITLE
Add coordinate and wind rotation

### PR DESCRIPTION
**Pull request by sandorkertesz**
Needed for https://github.com/ecmwf/anemoi-datasets/issues/2

The PR adds:
- rotate.rotate()
- rotate.unrotate()
- rotate.rotate_vector()
- rotate.unrotate_vector()
- coord.latlon_to_xyz()
- coord.xyz_to_latlon()

See documentation at: https://earthkit-geo.readthedocs.io/en/feature-rotate-wind/_api/geo/index.html

Gallery example: https://earthkit-geo.readthedocs.io/en/feature-rotate-wind/examples/rotate.html

### CODE REVIEW

**Comment by pmaciel** [comment]
Excellent, especially for the find of a malfunction :-)

I have extended the testing, to include these new tests which follow a different implementation, I haven't yet found a difference to the case (lon, lat) to (x, y, z). But, I'm still looking...

**Comment by sandorkertesz** [comment]
@pmaciel 
in the `rotate.unrotate_wind()` method the `lat` and `lat_unrotated` args are not used. Should we remove them?

**Comment by pmaciel** [comment]
> @pmaciel 
> in the `rotate.unrotate_wind()` method the `lat` and `lat_unrotated` args are not used. Should we remove them?

I would instead remove `lon_unrotated`, `lat_unrotated` so that it would resemble the other unrotate method (or these could be optional, because they can be computed). Maybe make them optional, default to None, calculate then if not provided. Ideally as scalars, or arrays. This allows for a consistent interface of the two unrotate_wind methods

**Comment by sandorkertesz** [comment]
> I would instead remove `lon_unrotated`, `lat_unrotated` so that it would resemble the other unrotate method (or these could be optional, because they can be computed). Maybe make them optional, default to None, calculate then if not provided. Ideally as scalars, or arrays. This allows for a consistent interface of the two unrotate_wind methods

You mean like this:
```python
def unrotate_wind(
    lat,
    lon,
    x_wind,
    y_wind,
    south_pole_latitude,
    south_pole_longitude,
    south_pole_rotation_angle=0,
    lat_unrotated=None,
    lon_unrotated=None,
):
```

**Comment by pmaciel** [comment]
> > I would instead remove `lon_unrotated`, `lat_unrotated` so that it would resemble the other unrotate method (or these could be optional, because they can be computed). Maybe make them optional, default to None, calculate then if not provided. Ideally as scalars, or arrays. This allows for a consistent interface of the two unrotate_wind methods
> 
> You mean like this:
> 
> ```python
> def unrotate_wind(
>     lat,
>     lon,
>     x_wind,
>     y_wind,
>     south_pole_latitude,
>     south_pole_longitude,
>     south_pole_rotation_angle=0,
>     lat_unrotated=None,
>     lon_unrotated=None,
> ):
> ```

Yes, exactly

**Comment by pmaciel** [comment]
> ```python
> x_wind
> ```

I'm not too sure of x_wind, y_wind -- but I understand it. I would suggest instead the usual (u, v) as the variables typically denote vector components, are in common use to describe wind components (including in our own shortName), and "wind" is already in the method's name. I think this would change a couple of method signatures

**Comment by sandorkertesz** [comment]
> I'm not too sure of x_wind, y_wind -- but I understand it. I would suggest instead the usual (u, v) as the variables typically denote vector components, are in common use to describe wind components (including in our own shortName), and "wind" is already in the method's name. I think this would change a couple of method signatures

Actually, this should work for any vector quantity. So the method name should be `rotate_vector`, `unrotate_vector` and the components `x_component` and `y_component`.

**Comment by sandorkertesz** [comment]
I renamed "wind" -> "vector", "x_wind" -> "x_component", "y_wind" -> "y-component" and also added a gallery example for `rotate()`.

TODO:
 - add reference to the MIR code in the relevant methods (I need help from @pmaciel to do this)
 - if we want to add the "rotate" part of `unrotate_vector()` we should review the method names since we already have a `rotate_vector()`

**Pull request merged**
